### ISSUE TITLE
Possible regression when we intentionally do not specify project per Pulumi stack. 

### ISSUE THREAD

**Issue by jkisk** [pulumi/pulumi-google-native#666] opened 2022-08-30 20:58 UTC
👋🏼 I think this PR might have broken a use case when we intentionally do not specify project per Pulumi stack. In my case it's a) ensure project is explicitly specified on every resource _and_ b) Pulumi stack spans multiple GCP projects hence setting "global default" is risky.

This is what I'm seeing after upgrading google-native from 0.23 to 0.24:

```
    error: unable to find a valid Project. Set the Project by using:

     	 • `pulumi config set google-native:project my-project` or
     	 • Environment variables: `GOOGLE_PROJECT`, `GOOGLE_CLOUD_PROJECT`, `GCLOUD_PROJECT` or `CLOUDSDK_CORE_PROJECT`
```

_Originally posted by @bai in https://github.com/pulumi/pulumi-google-native/issues/636#issuecomment-1229397466_

**Comment by viveklak** [comment] 2022-08-30 21:54
Should this be a duplicate of #664 or vice versa?

**Comment by jkisk** [comment] 2022-08-30 22:53
I believe related to: https://github.com/pulumi/pulumi-google-native/issues/565, we are enforcing project as required, but it is not required if the project is specified within every resource.

**Comment by jkisk** [comment] 2022-08-30 22:54
> Should this be a duplicate of #664 or vice versa?

I believe they address different issues, although they both center around acceptable ways to configure the Google Project value.

**Closed** 2022-09-01 13:59 UTC
Labels: kind/bug

**Comment by viveklak** [comment] 2022-09-01 14:24
> Looks like legacy GCP adapter is also now a subject to the same breaking change: [pulumi/pulumi-gcp#882](https://github.com/pulumi/pulumi-gcp/pull/882)

@guineveresaenger FYI ^
