### ISSUE TITLE
Cannot update docker image for a Cloud Run service with a fixed name

### ISSUE THREAD

**Issue by jadengis** [pulumi/pulumi-google-native#204] opened 2021-09-26 05:42 UTC
In v0.7 when attempting to update the docker image used by a Cloud Run service, pulumi incorrectly generates a replace instead of an update. What happens is that the existing Cloud Run gets marked for deletion and a replacement is attempted but Google Cloud returns a 409 because the existing service hasn't been removed yet. This ruins the pulumi state because eventually the existing Cloud Run service is deleted but pulumi thinks is still exists. Manually intervention is required to fix and this will break production deployments (deletes a service without a replacement).

In v0.6 and below, the same pulumi code generated an update and things worked as expected.

## Steps to reproduce

1. Create a container in your pulumi files, e.g.
```typescript
export const apiImage = new docker.Image(imageName, {
  imageName: pulumi.interpolate`gcr.io/${config.project}/${imageName}:latest`,
  build: {
    context: config.projectRoot,
    dockerfile: path.join(config.projectRoot, "apps/api/Dockerfile"),
  },
});
```
2. Use the above docker image in a cloud run service, e.g.:
```typescript
export const apiService = new gcloud.run.v1.Service(groupPrefix, {
  project,
  location,
  kind: "Service",
  apiVersion: "serving.knative.dev/v1",
  spec: {
    template: {
      spec: {
        containerConcurrency: api.concurrency,
        serviceAccountName: serviceAccount.email,
        containers: [
          {
            image: apiImage.imageName,
            ports: [{ containerPort: api.port }],
          },
        ],
      },
    },
    traffic: [{ latestRevision: true, percent: 100 }],
  },
});
```
3. Deploy the service using `pulumi up`
4. Change the code in the container and run `pulumi up` again. The command will fail.

Expected:  Pulumi will generate and update for a Cloud Run service when changing the underlying docker image.
Actual:  Pulumi generates a replacement which breaks the deployment and leaves the state inconsistent.

**Comment by jadengis** [comment] 2021-09-27 03:44
Looking at the commits in the v0.7 release, I would assume https://github.com/pulumi/pulumi-google-native/pull/181 is a likely candidate for introducing this regression.

**Comment by mikhailshilkov** [comment] 2021-09-27 08:55
Yes, this sounds like a dupe of https://github.com/pulumi/pulumi-google-native/issues/185

**Comment by mikhailshilkov** [comment] 2021-09-27 08:56
I'll close as a dupe - we'll check this scenario while fixing #185

**Closed by mikhailshilkov** 2021-09-27 08:56 UTC
Labels: kind/bug, resolution/duplicate
