### ISSUE TITLE
compute.v1.Network.get fails

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-google-native#328] opened 2022-02-03 20:48 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Calling `Network.get` fails with: `error: Preview failed: Import is not yet implemented`

### Steps to reproduce

```typescript
const PlumsVPC = pulumi.compute.v1.Network.get(
  "my-vpc",
  `projects/my-project/global/networks/my-vpc`
);

```

Expected: It'd get the VPC object
Actual: 
```
 google-native:compute/v1:Network (my-vpc):
    error: Preview failed: Import is not yet implemented
```

**Comment by danielrbradley** [comment] 2022-02-08 10:56
Closing as a duplicate of #81

**Closed by danielrbradley** 2022-02-08 10:56 UTC
Labels: kind/bug, resolution/duplicate
