### ISSUE TITLE
Feature Request - native.sqladmin.v1.User resource

### ISSUE THREAD

**Issue by ColeSiegelTR** [pulumi/pulumi-google-native#321] opened 2022-02-02 20:10 UTC
Hi, I'm looking to manipulate a user resource as exposed by this API - https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/users

The legacy library has it but I do not see it in the Google Native library: https://www.pulumi.com/registry/packages/gcp/api-docs/sql/user/

Thanks!

**Comment by danielrbradley** [comment] 2022-02-07 14:26
Currently we can't generate resources for sqladmin users because the specification doesn't give us a way of getting a single user - only listing users (see: https://github.com/pulumi/pulumi-google-native/issues/47).

Closing as duplicate of #244

**Closed by danielrbradley** 2022-02-07 14:26 UTC
Labels: resolution/duplicate, kind/enhancement
