### ISSUE TITLE
repositoryId is a required field

### ISSUE THREAD

**Issue by antstanley** [pulumi/pulumi-google-native#438] opened 2022-04-11 09:49 UTC
File: [themes/default/content/registry/packages/google-native/api-docs/artifactregistry/v1/repository/_index.md](https://www.pulumi.com/registry/packages/google-native/api-docs/artifactregistry/v1/repository/)

As per pulumi/pulumi-google-native#436 the `repositoryId` field is required to create and Artifact Registry Repository. Please can you mark it as required in the docs.

**Comment by jkodroff** [comment] 2022-04-12 18:15
Confirmed this field is indeed required in the Google Classic Provider: https://www.pulumi.com/registry/packages/gcp/api-docs/artifactregistry/repository/#repositoryid_nodejs

**Comment by jkodroff** [comment] 2022-04-12 18:35
Duplicate of #436

**Closed by jkodroff** 2022-04-12 18:35 UTC
Labels: kind/bug, resolution/duplicate
